services:
  - type: web
    name: finmitra-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    branch: main
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 8085
      - key: DATABASE_URL
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
