server:
  port: 8085

spring:
  application:
    name: finmitra

  datasource:
    url: jdbc:mysql://localhost:3306/finmitra_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: RootPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT Configuration
app:
  jwt-secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jwt-expiration-milliseconds: 86400000 # 24 hours
